### ISSUE TITLE
Please update to 4.1.1

### ISSUE THREAD

**Issue by neworld** [stasson/vd-tool#7]
This repo is amazing for automating convert. Thanks for providing a clean way to use it. However, the tool is a bit outdated.

**Comment by Shebella** [comment]
@stasson @neworld 
Please find my Pull Request here 
https://github.com/stasson/vd-tool/pull/13
I built the **vd-tool** from the latest version of Android Studio source code which branch is **studio-2020.3.1**
https://android.googlesource.com/platform/tools/base/+/refs/tags/studio-2020.3.1/vector-drawable-tool

**Comment by AlanChiou** [comment]
Hi @stasson,
Do you have any update here?

**Comment by stasson** [comment]
sorry was busy at office will do asap

**Comment by stasson** [comment]
+ vd-tool@4.0.2

plz let me know if any issue.
